// <auto-generated />
using System;
using APIrest_DAD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIrest_DAD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528101412_M03-AddTableNotificacao")]
    partial class M03AddTableNotificacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIrest_DAD.Models.Notificacao", b =>
                {
                    b.Property<int>("codigoNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoNotificacao"));

                    b.Property<int>("codigoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataNotificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("dataPreNotificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("codigoNotificacao");

                    b.ToTable("SERV_NOTIFICACAO");
                });
#pragma warning restore 612, 618
        }
    }
}
